# Generated by Django 5.0.6 on 2024-06-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(verbose_name='decription')),
                ('price', models.PositiveIntegerField(default=1000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
