# Generated by Django 5.0.6 on 2024-06-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topgadgets',
            name='price',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
